baseurl = "https://mvanbrummen.github.io/"
languageCode = "en-gb"
title = "Michael Van Brummen"
theme = "hugo-type-theme"
# Enable comments by entering your Disqus shortname
disqusShortname = "mvanbrummen.github.io"
# Add your tracking code to enable Google Analytics
googleAnalytics = "UA-86752867-1"
# Posts per page
paginate = 10


[params]
	author = "Michael Van Brummen"
	description = "From the mind and keyboard of MVB..."
	# The keywords will be added as a meta tag. Delimit them with a comma.
	keywords = "java,programming,go,golang,software"
	# Either show custom avatar on the top
	# left by adding the filename in below
	avatar = "img/me.jpg"
	# or use Gravatar by adding your email address to generate a unique avatar
	gravatar = ""

	headerText = "Currently @CoreLogic. Interested in Scala, Go, open source and startups."
	# To add a header background to the main site, save your image under static/img/.
	# If no image path is provided, a orange background will be shown instead.
	headerImage = ""
	copyright = "Michael Van Brummen<br>Powered by [Hugo](//gohugo.io/)"


	[params.social]
		# Insert your accout name and the icon will be shown in the right menu
		rss = false
		homepage = true
		email = "michaelvanbrummen@gmail.com"
		behance = ""
		bitbucket = ""
		dribbble = ""
		facebook = ""
		flickr = ""
		github = "mvanbrummen"
		googleplus = ""
		instagram = ""
		linkedin = "https://au.linkedin.com/in/michael-van-brummen"
		pinterest = ""
		reddit = ""
		soundcloud = ""
		stackexchange = ""
		steam = ""
		tumblr = ""
		twitter = ""
		wordpress = ""
		youtube = ""
		gitlab = "mvanbrummen"
		# Insert your Xing Profile-ID not your login name
		xing = ""
